/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.TPBD.views.Clientes;

import com.TPBD.Business.ClienteBusiness;
import com.TPBD.Frontier.Entidades.ClienteEntidade;
import com.TPBD.Frontier.Entidades.EmpresaEntidade;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author IanCarlosAfonsodaSil
 */
public class Cadastro extends javax.swing.JFrame {

    private ClienteBusiness clienteBusiness;
    private ArrayList<EmpresaEntidade> empresaList;
    private String[] defaultListModel;
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        this.clienteBusiness = new ClienteBusiness();
        this.empresaList = new ArrayList();
        defaultListModel = this.geraListaModelEmpresa();
        initComponents();
    }
    
    public Cadastro(ArrayList<EmpresaEntidade> empresaList) {
        this.clienteBusiness = new ClienteBusiness();
        this.empresaList = empresaList;
        defaultListModel = this.geraListaModelEmpresa();
        initComponents();
    }

    private String[] geraListaModelEmpresa() {
        ArrayList<String> aux = new ArrayList();
        if(!empresaList.isEmpty()) {
            aux.add("Sem vínculo com empresa");
            for(int i=0; i < empresaList.size(); i++){
                aux.add(empresaList.get(i).getRazaoSocial());
            }
        } else {
            aux.add("Lista Vazia!");
            
        }
        String[] teste = new String[aux.size()];
        teste = aux.toArray(teste);
        
        return teste;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JClienteNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JClienteCPF = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JClienteTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JClienteEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JClienteCidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JClienteEndereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JClienteCEP = new javax.swing.JTextField();
        JEmpresaList = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadastro de Clientes");

        jLabel2.setText("Nome");

        JClienteNome.setToolTipText("Nome");
        JClienteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JClienteNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("CPF");

        JClienteCPF.setToolTipText("CPF");
        JClienteCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JClienteCPFActionPerformed(evt);
            }
        });

        SaveButton.setText("Salvar");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefone");

        JClienteTelefone.setToolTipText("Telefone");
        JClienteTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JClienteTelefoneActionPerformed(evt);
            }
        });

        jLabel5.setText("E-Mail");

        JClienteEmail.setToolTipText("Email");
        JClienteEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JClienteEmailActionPerformed(evt);
            }
        });

        jLabel6.setText("Cidade");

        JClienteCidade.setToolTipText("Cidade");
        JClienteCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JClienteCidadeActionPerformed(evt);
            }
        });

        jLabel7.setText("Endereço");

        JClienteEndereco.setToolTipText("Endereço");
        JClienteEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JClienteEnderecoActionPerformed(evt);
            }
        });

        jLabel8.setText("CEP");

        JClienteCEP.setToolTipText("CEP");
        JClienteCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JClienteCEPActionPerformed(evt);
            }
        });

        JEmpresaList.setModel(new DefaultComboBoxModel(this.geraListaModelEmpresa()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SaveButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)
                        .addGap(79, 79, 79))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(152, 152, 152)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JClienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(JClienteEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(JClienteCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JClienteNome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JClienteCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JClienteCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(JEmpresaList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(104, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JEmpresaList)
                    .addComponent(JClienteNome, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JClienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JClienteCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JClienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JClienteEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JClienteCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(cancelButton))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JClienteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JClienteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JClienteNomeActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        ClienteEntidade cliente = new ClienteEntidade();
        
        cliente.setCep(this.JClienteCEP.getText());
        cliente.setCidade(this.JClienteCidade.getText());
        cliente.setCpf(this.JClienteCPF.getText());
        cliente.setEmail(this.JClienteEmail.getText());
        cliente.setEndereco(this.JClienteEndereco.getText());
        cliente.setNome(this.JClienteNome.getText());
        cliente.setTelefone(this.JClienteTelefone.getText());
        
        int idSelected = this.JEmpresaList.getSelectedIndex();
        if(idSelected - 1 > 0)
            cliente.setIdEmpresa(this.empresaList.get(idSelected - 1).getId());
        else
            cliente.setIdEmpresa(java.sql.Types.NULL);
        //
        int status = clienteBusiness.insereCliente(cliente);
        if(status == 0){
            this.JClienteCEP.setText("");
            this.JClienteCidade.setText("");
            this.JClienteCPF.setText("");
            this.JClienteEmail.setText("");
            this.JClienteEndereco.setText("");
            this.JClienteNome.setText("");
            this.JClienteTelefone.setText("");
            this.JEmpresaList.setSelectedIndex(0);
        }
        
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void JClienteCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JClienteCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JClienteCPFActionPerformed

    private void JClienteTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JClienteTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JClienteTelefoneActionPerformed

    private void JClienteEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JClienteEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JClienteEmailActionPerformed

    private void JClienteCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JClienteCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JClienteCidadeActionPerformed

    private void JClienteEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JClienteEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JClienteEnderecoActionPerformed

    private void JClienteCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JClienteCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JClienteCEPActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JClienteCEP;
    private javax.swing.JTextField JClienteCPF;
    private javax.swing.JTextField JClienteCidade;
    private javax.swing.JTextField JClienteEmail;
    private javax.swing.JTextField JClienteEndereco;
    private javax.swing.JTextField JClienteNome;
    private javax.swing.JTextField JClienteTelefone;
    private javax.swing.JComboBox<String> JEmpresaList;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
