/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.TPBD.views.Fluxo;

import com.TPBD.Business.FluxoVeiculoBusiness;
import com.TPBD.Frontier.Entidades.FluxoVeiculoEntidade;
import com.TPBD.Frontier.Entidades.VagaEntidade;
import com.TPBD.Frontier.Entidades.VeiculoEntidade;
import com.TPBD.views.Veiculos.VeiculosView;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

/**
 *
 * @author IanCarlosAfonsodaSil
 */
public class EntradaVeiculos extends javax.swing.JFrame {
    
    private FluxoVeiculoBusiness fluxoBusiness;
    private FluxoVeiculoEntidade fluxo;
    private ArrayList<VeiculoEntidade> veiculoList;
    private ArrayList<VagaEntidade> vagaLivreList;
    private boolean vagaManual = true;
    /**
     * Creates new form EntradaVeiculos
     */
    public EntradaVeiculos() {
        this.fluxoBusiness = new FluxoVeiculoBusiness();
        this.fluxo = new FluxoVeiculoEntidade();
        this.veiculoList = this.fluxoBusiness.veiculoBusiness.listaVeiculosNaoEstacionados();
        this.vagaLivreList = this.fluxoBusiness.vagaBusiness.buscaListaVagasLivres();
        
        initComponents();
    }

    private String[] geraListaModelComboBox(ArrayList obList, String nomeCampo) {
        ArrayList<String> aux = new ArrayList();
        if(!obList.isEmpty()) {
            for(int i=0; i < obList.size(); i++){
                if(nomeCampo.equals("veiculo")) {
                    VeiculoEntidade veiculo = (VeiculoEntidade) obList.get(i);
                    aux.add(veiculo.getPlaca());
                }
                if(nomeCampo.equals("vaga")) {
                    VagaEntidade vaga = (VagaEntidade) obList.get(i);
                    aux.add(vaga.getNomeVaga());
                }
            }
        } 
        String[] teste = new String[aux.size()];
        teste = aux.toArray(teste);
        
        return teste;
    }
    
    private int obtemIndexGenerico(ArrayList obList, String nomeCampo, int idFromCombox) {
        //Implementar o obtem Index para vagas e para veículos
        for(int i =0; i < obList.size(); i++) {
            if(nomeCampo.equals("veiculo")){
                if(idFromCombox == i){
                    return i;
                }
            }
            if(nomeCampo.equals("vaga")){
                if(idFromCombox == i){
                    return i;
                }
            }
        }
        return -1;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JComboVeiculos = new javax.swing.JComboBox<>();
        JBnovoVeiculo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        JComboVagas = new javax.swing.JComboBox<>();
        JSubmitButton = new javax.swing.JButton();
        JCancelButton = new javax.swing.JButton();
        JControleManualB = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Entrada de veículo");

        jLabel2.setText("Veículos já cadastrados");

        JComboVeiculos.setModel(new DefaultComboBoxModel(this.geraListaModelComboBox(this.veiculoList, "veiculo"))

        );

        JBnovoVeiculo.setText("Ir para Veículos");
        JBnovoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnovoVeiculoActionPerformed(evt);
            }
        });

        jLabel3.setText("Vagas Disponíveis");

        JComboVagas.setModel(new DefaultComboBoxModel(this.geraListaModelComboBox(this.vagaLivreList, "vaga"))
        );
        this.JComboVagas.setEnabled(false);

        JSubmitButton.setText("Autorizar Entrada");
        JSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSubmitButtonActionPerformed(evt);
            }
        });

        JCancelButton.setText("Cancelar");
        JCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCancelButtonActionPerformed(evt);
            }
        });

        JControleManualB.setText("Controle de vagas Manual");
        JControleManualB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JControleManualBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(JComboVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(JBnovoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JControleManualB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JSubmitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JComboVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBnovoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JComboVeiculos))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JControleManualB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JComboVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSubmitButtonActionPerformed
        // TODO add your handling code here:
        int vagaIndex;
        
        int idVagaFromCombox = this.JComboVagas.getSelectedIndex();
        if(this.vagaManual){
            vagaIndex = this.obtemIndexGenerico(this.vagaLivreList, "vaga", this.JComboVagas.getSelectedIndex());
        } else {
            vagaIndex = this.vagaLivreList.get(0).getId();
        }
        int idVeiculoFromCombox = this.JComboVeiculos.getSelectedIndex();
        
        this.fluxo.setIdVaga(vagaLivreList.get(vagaIndex).getId());
        this.fluxo.setIdVeiculo(veiculoList.get(this.obtemIndexGenerico(veiculoList, "veiculo", idVeiculoFromCombox)).getId());
        this.fluxo.setGerarRecibo("0");
        
        int status = this.fluxoBusiness.cadastraFluxo(fluxo);
        if(status == 0) {
            //Limpa a tela, refaz as listas, blablabla
        }
    }//GEN-LAST:event_JSubmitButtonActionPerformed

    private void JCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JCancelButtonActionPerformed

    private void JControleManualBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JControleManualBActionPerformed
        // TODO add your handling code here:
        if(this.JControleManualB.isSelected()){
            this.vagaManual = true;
            this.JComboVagas.setEnabled(true);
        } else {
            this.vagaManual = false;
            this.JComboVagas.setEnabled(false);
        }
        
    }//GEN-LAST:event_JControleManualBActionPerformed

    private void JBnovoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnovoVeiculoActionPerformed
        // TODO add your handling code here:
        VeiculosView veiculosView = new VeiculosView();
        veiculosView.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        veiculosView.setVisible(true);
    }//GEN-LAST:event_JBnovoVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntradaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntradaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntradaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBnovoVeiculo;
    private javax.swing.JButton JCancelButton;
    private javax.swing.JComboBox<String> JComboVagas;
    private javax.swing.JComboBox<String> JComboVeiculos;
    private javax.swing.JToggleButton JControleManualB;
    private javax.swing.JButton JSubmitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
