/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.TPBD.views.Fluxo;

import com.TPBD.Business.FluxoVeiculoBusiness;
import com.TPBD.Frontier.Entidades.FluxoVeiculoEntidade;
import com.TPBD.Frontier.Entidades.VeiculoEntidade;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author IanCarlosAfonsodaSil
 */
public class SaidaVeiculos extends javax.swing.JFrame {
    
    private FluxoVeiculoBusiness fluxoVeiculoBusiness;
    private ArrayList<VeiculoEntidade> veiculosEstacionadosList;
    private ArrayList<FluxoVeiculoEntidade> fluxosAbertosList;
    /**
     * Creates new form SaidaVeiculos
     */
    public SaidaVeiculos() {
        fluxoVeiculoBusiness = new FluxoVeiculoBusiness();
        veiculosEstacionadosList = this.geraVeiculosEstacionadosList();
        initComponents();
    }
    private DefaultListModel geraVeiculosEstacionadosListModel(){
        ArrayList<VeiculoEntidade> a = this.geraVeiculosEstacionadosList();
        DefaultListModel listModel = new DefaultListModel();
        for(int i=0; i< a.size(); i++){
            listModel.addElement(a.get(i).getPlaca());
        }
        return listModel;
    }
    
    private ArrayList <VeiculoEntidade> geraVeiculosEstacionadosList(){
        this.fluxosAbertosList = this.fluxoVeiculoBusiness.listaFluxosAbertos();
        this.veiculosEstacionadosList = new ArrayList();
        for(int i=0; i < this.fluxosAbertosList.size(); i++) {
            this.veiculosEstacionadosList.add(this.fluxoVeiculoBusiness.veiculoBusiness.buscaVeiculo(this.fluxosAbertosList.get(i).getIdVeiculo()));
        }
        return veiculosEstacionadosList;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListVeiculosEstacionados = new javax.swing.JList<>();
        JSaidaButton = new javax.swing.JButton();
        JCancelButton = new javax.swing.JButton();
        JLHorario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JLHorarioText = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JFVeiculoInfo = new javax.swing.JTextPane();
        StyledDocument doc = JFVeiculoInfo.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Saída de veículo");

        JListVeiculosEstacionados.setModel(this.geraVeiculosEstacionadosListModel());
        JListVeiculosEstacionados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JListVeiculosEstacionadosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(JListVeiculosEstacionados);

        JSaidaButton.setText("Autorizar Saída");
        JSaidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSaidaButtonActionPerformed(evt);
            }
        });

        JCancelButton.setText("Cancelar");

        JLHorario.setText("Horário Entrada");

        jLabel3.setText("Veículos Estacionados");

        JLHorarioText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLHorarioText.setForeground(new java.awt.Color(204, 0, 0));
        JLHorarioText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        JFVeiculoInfo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        JFVeiculoInfo.setEnabled(false);
        JFVeiculoInfo.setOpaque(false);
        jScrollPane3.setViewportView(JFVeiculoInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLHorarioText, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(JLHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JSaidaButton)
                .addGap(35, 35, 35)
                .addComponent(JCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JLHorarioText, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSaidaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JListVeiculosEstacionadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JListVeiculosEstacionadosMousePressed
        // TODO add your handling code here:
        VeiculoEntidade veiculo = veiculosEstacionadosList.get(this.JListVeiculosEstacionados.getSelectedIndex());
        FluxoVeiculoEntidade fluxoAtual = fluxosAbertosList.get(this.JListVeiculosEstacionados.getSelectedIndex());
        
        this.JFVeiculoInfo.setText("Informações do Veículo\n"
                +"\nMarca: "+veiculo.getMarca()
                +"\nModelo: "+veiculo.getModelo()
                +"\nPlaca: "+veiculo.getPlaca()
        );
        if(fluxoAtual.getHorarioEntrada()!= null)
            this.JLHorarioText.setText(fluxoAtual.getHorarioEntrada().format(DateTimeFormatter.ISO_LOCAL_TIME));
        else {
            this.JLHorarioText.setText("");
        }
    }//GEN-LAST:event_JListVeiculosEstacionadosMousePressed

    private void JSaidaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSaidaButtonActionPerformed
        // TODO add your handling code here:
        FluxoVeiculoEntidade fluxoAbertoSelecionado = fluxosAbertosList.get(this.JListVeiculosEstacionados.getSelectedIndex());
        int status = this.fluxoVeiculoBusiness.finalizaFluxoAberto(fluxoAbertoSelecionado.getId());
        if(status == 0) {
            //atualizar as listas e exibir mensagem de saída
        }
    }//GEN-LAST:event_JSaidaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaidaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaidaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaidaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaidaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaidaVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JCancelButton;
    private javax.swing.JTextPane JFVeiculoInfo;
    private javax.swing.JLabel JLHorario;
    private javax.swing.JLabel JLHorarioText;
    private javax.swing.JList<String> JListVeiculosEstacionados;
    private javax.swing.JButton JSaidaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
