/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.TPBD.views.Recibos;

import com.TPBD.Business.ClienteBusiness;
import com.TPBD.Business.EmpresaBusiness;
import com.TPBD.Business.ReciboBusiness;
import com.TPBD.Business.VeiculoBusiness;
import com.TPBD.Frontier.Entidades.ClienteEntidade;
import com.TPBD.Frontier.Entidades.EmpresaEntidade;
import com.TPBD.Frontier.Entidades.ReciboEntidade;
import com.TPBD.Frontier.Entidades.VeiculoEntidade;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author IanCarlosAfonsodaSil
 */
public class RecibosFiltros extends javax.swing.JFrame {
    private ArrayList<ReciboEntidade> listaRecibos;
    private String[] defaultListModel;
    
    
    private ReciboBusiness reciboBusiness;
    private VeiculoBusiness veiculoBusiness;
    private EmpresaBusiness empresaBusiness;
    private ClienteBusiness clienteBusiness;
    /**
     * Creates new form RecibosFiltros
     */
    public RecibosFiltros() {
        this.reciboBusiness = new ReciboBusiness();
        this.veiculoBusiness = new VeiculoBusiness();
        this.empresaBusiness = new EmpresaBusiness();
        this.clienteBusiness = new ClienteBusiness();
        
        listaRecibos = reciboBusiness.buscaRecibosNaoPagos();
        
        defaultListModel = this.geraListaModel(listaRecibos, "recibos");
        
        initComponents();
    }

    private String[] geraListaModel(ArrayList list, String tipo){
        ArrayList<String> aux = new ArrayList();
        
        if(tipo.equals("recibos")){
            ArrayList<ReciboEntidade> lista = list;
            ArrayList<VeiculoEntidade> veiculoList = veiculoBusiness.listaVeiculos();
            if(!lista.isEmpty()) {
                for(int i=0; i < lista.size(); i++){
                    for(int j=0; j< veiculoList.size(); j++) {
                        if(veiculoList.get(j).getId() == lista.get(i).getIdVeiculo()){
                            aux.add(veiculoList.get(j).getPlaca());
                        }
                    }
                }
            }
        }
        if(tipo.equals("empresa")){
            ArrayList<EmpresaEntidade> lista = list;
            if(!lista.isEmpty()){
                for(int i=0; i < lista.size(); i++){
                    aux.add(lista.get(i).getRazaoSocial());
                }
            }
        }
        if(tipo.equals("cliente")){
            ArrayList<ClienteEntidade> lista = list;
            if(!lista.isEmpty()){
                for(int i=0; i < lista.size(); i++){
                    aux.add(lista.get(i).getNome());
                }
            }
        }
        String[] teste = new String[aux.size()];
        teste = aux.toArray(teste);
        
        return teste;
    }
    
    public String preparaDadosRecibo(String placa) {
        ArrayList<VeiculoEntidade> veiculoList = this.veiculoBusiness.listaVeiculos();
        VeiculoEntidade veiculo = new VeiculoEntidade();
        for(int i=0; i < veiculoList.size(); i++){
            if(veiculoList.get(i).getPlaca().equals(placa))
                veiculo = veiculoList.get(i);
        }
        ReciboEntidade recibo = new ReciboEntidade();
        for(int j=0; j< this.listaRecibos.size(); j++){
            if(this.listaRecibos.get(j).getIdVeiculo() == veiculo.getId()){
                recibo = this.listaRecibos.get(j);
            }
        }
        return "Dados do recibo"
                + "\nVeículo: "+ veiculo.getMarca()+" "+veiculo.getModelo()+"\n"+veiculo.getPlaca()+
                "\nEntrada: "+recibo.getHorarioEntrada().format(DateTimeFormatter.ISO_TIME) +
                "\nSaída: "+recibo.getHorarioSaida().format(DateTimeFormatter.ISO_TIME) +
                "\nValor: "+recibo.getValor()
                ;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JComboCliente = new javax.swing.JComboBox<>();
        JComboEmpresa = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        JComboRecibos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JBFCliente = new javax.swing.JButton();
        JBFEmpresa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RECIBOS");

        JComboCliente.setModel(new DefaultComboBoxModel(this.geraListaModel(this.clienteBusiness.buscaListaCliente(), "cliente"))
        );

        JComboEmpresa.setModel(new DefaultComboBoxModel(this.geraListaModel(this.empresaBusiness.listaEmpresas(), "empresa"))
        );

        jButton1.setText("Pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JComboRecibos.setModel(new DefaultComboBoxModel(this.geraListaModel(this.listaRecibos, "recibos"))
        );
        JComboRecibos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JComboRecibosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JComboRecibosMouseReleased(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        JBFCliente.setText("Filtrar Cliente");
        JBFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBFClienteActionPerformed(evt);
            }
        });

        JBFEmpresa.setText("Filtrar Empresa");
        JBFEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBFEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JComboRecibos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JComboCliente, 0, 99, Short.MAX_VALUE)
                            .addComponent(JComboEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JBFCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JBFEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JComboRecibos)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JComboEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(JBFEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JComboCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(JBFCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JComboRecibosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JComboRecibosMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JComboRecibosMouseReleased

    private void JComboRecibosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JComboRecibosMouseClicked
        // TODO add your handling code here:
        this.jTextArea1.setText(this.preparaDadosRecibo(this.JComboRecibos.getSelectedItem().toString()));
    }//GEN-LAST:event_JComboRecibosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ReciboEntidade recibo = this.reciboBusiness.buscaReciboAbertoPorPlaca(this.JComboRecibos.getSelectedItem().toString());
        recibo.setPago("1");
        int status = this.reciboBusiness.editaRecibo(recibo.getId(), recibo);
        
        if(status == 0) {
            JOptionPane.showMessageDialog(this, "Recibo Pago!", "Pagamento de Recibo", JOptionPane.INFORMATION_MESSAGE);
            listaRecibos = this.reciboBusiness.buscaRecibosNaoPagos();
            this.JComboRecibos.setModel(new DefaultComboBoxModel(this.geraListaModel(listaRecibos, "recibos")));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JBFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBFClienteActionPerformed
        // TODO add your handling code here:
        String cliente = this.JComboCliente.getSelectedItem().toString();
        int idCliente = -1;
        ArrayList<ClienteEntidade> clienteList = this.clienteBusiness.buscaListaCliente();
        for(int i=0; i< clienteList.size(); i++) {
            if(clienteList.get(i).getNome().equals(cliente)){
                idCliente = clienteList.get(i).getId();
            }
        }
        listaRecibos = this.reciboBusiness.buscaRecibosPorClienteAberto(idCliente);
        this.JComboRecibos.setModel(new DefaultComboBoxModel(this.geraListaModel(listaRecibos, "recibos")));

    }//GEN-LAST:event_JBFClienteActionPerformed

    private void JBFEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBFEmpresaActionPerformed
        // TODO add your handling code here:
        String empresa = this.JComboEmpresa.getSelectedItem().toString();
        listaRecibos = this.reciboBusiness.buscaRecibosPorNomeEmpresaAberto(empresa);
        this.JComboRecibos.setModel(new DefaultComboBoxModel(this.geraListaModel(listaRecibos, "recibos")));

    }//GEN-LAST:event_JBFEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecibosFiltros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecibosFiltros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecibosFiltros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecibosFiltros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecibosFiltros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBFCliente;
    private javax.swing.JButton JBFEmpresa;
    private javax.swing.JComboBox<String> JComboCliente;
    private javax.swing.JComboBox<String> JComboEmpresa;
    private javax.swing.JComboBox<String> JComboRecibos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
