/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.TPBD.views.Veiculos;

import com.TPBD.Business.VeiculoBusiness;
import com.TPBD.Frontier.Entidades.ClienteEntidade;
import com.TPBD.Frontier.Entidades.VeiculoEntidade;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author IanCarlosAfonsodaSil
 */
public class Edicao extends javax.swing.JFrame {

    private VeiculoEntidade veiculo;
    private VeiculoBusiness veiculoBusiness;
    private String[] defaultListModel;
    private ArrayList<ClienteEntidade> clienteList;
    
    /**
     * Creates new form Edicao
     * @param veiculo
     */
    public Edicao(VeiculoEntidade veiculo) {
        this.veiculo = veiculo;
        this.veiculoBusiness = new VeiculoBusiness();
        this.clienteList = new ArrayList();
        this.defaultListModel = this.geraListaModelCliente();
        initComponents();
    }
    
    public Edicao(VeiculoEntidade veiculo, ArrayList<ClienteEntidade> clienteList) {
        this.veiculo = veiculo;
        this.veiculoBusiness = new VeiculoBusiness();
        this.clienteList = clienteList;
        this.defaultListModel = this.geraListaModelCliente();
        initComponents();
    }
    
    public Edicao(){}

    private String[] geraListaModelCliente() {
        ArrayList<String> aux = new ArrayList();
        if(!clienteList.isEmpty()) {
            for(int i=0; i < clienteList.size(); i++){
                aux.add(clienteList.get(i).getNome());
            }
        } else {
            aux.add("Lista Vazia!");
            
        }
        String[] teste = new String[aux.size()];
        teste = aux.toArray(teste);
        
        return teste;
    }
    
    private int obtemIndex() {
        if(this.veiculo.getIdCliente() > 0) {
            for(int i =0; i< this.clienteList.size(); i++) {
                if(this.veiculo.getIdCliente() == this.clienteList.get(i).getId()){
                    return i;
                }
            }
        }
        return 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        JLVeiculoPlaca6 = new javax.swing.JLabel();
        JVeiculoPlaca = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        JVeiculoMarca = new javax.swing.JTextField();
        SaveButton4 = new javax.swing.JButton();
        cancelButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        JVeiculoModelo = new javax.swing.JTextField();
        JClienteList = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel15.setText("Edicao de Veículos");

        JLVeiculoPlaca6.setText("Placa");

        JVeiculoPlaca.setText(this.veiculo.getPlaca());
        JVeiculoPlaca.setToolTipText("Placa");
        JVeiculoPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JVeiculoPlacaActionPerformed(evt);
            }
        });

        jLabel16.setText("Marca");

        JVeiculoMarca.setText(this.veiculo.getMarca());
        JVeiculoMarca.setToolTipText("Marca");
        JVeiculoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JVeiculoMarcaActionPerformed(evt);
            }
        });

        SaveButton4.setText("Salvar");
        SaveButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButton4ActionPerformed(evt);
            }
        });

        cancelButton4.setText("Cancelar");
        cancelButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton4ActionPerformed(evt);
            }
        });

        jLabel17.setText("Modelo");

        JVeiculoModelo.setText(this.veiculo.getModelo());
        JVeiculoModelo.setToolTipText("Modelo");
        JVeiculoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JVeiculoModeloActionPerformed(evt);
            }
        });

        JClienteList.setModel(new DefaultComboBoxModel(this.geraListaModelCliente())

        );
        JClienteList.setSelectedIndex(this.obtemIndex());

        jLabel5.setText("Proprietário");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLVeiculoPlaca6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(JVeiculoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JVeiculoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JVeiculoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(137, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SaveButton4)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton4)
                        .addGap(79, 79, 79))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JClienteList, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(JLVeiculoPlaca6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JVeiculoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JVeiculoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JVeiculoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JClienteList, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton4)
                    .addComponent(cancelButton4))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JVeiculoPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JVeiculoPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JVeiculoPlacaActionPerformed

    private void JVeiculoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JVeiculoMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JVeiculoMarcaActionPerformed

    private void SaveButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButton4ActionPerformed
        // TODO add your handling code here:
        veiculo.setMarca(this.JVeiculoMarca.getText());
        veiculo.setModelo(this.JVeiculoModelo.getText());
        veiculo.setPlaca(this.JVeiculoPlaca.getText());
        
        int idSelected = this.JClienteList.getSelectedIndex();
        veiculo.setIdCliente(this.clienteList.get(idSelected).getId());

        int status = veiculoBusiness.editaVeiculo(this.veiculo.getId(), veiculo);
        if(status == 0)
            this.dispose();
    }//GEN-LAST:event_SaveButton4ActionPerformed

    private void cancelButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButton4ActionPerformed

    private void JVeiculoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JVeiculoModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JVeiculoModeloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JClienteList;
    private javax.swing.JLabel JLVeiculoPlaca6;
    private javax.swing.JTextField JVeiculoMarca;
    private javax.swing.JTextField JVeiculoModelo;
    private javax.swing.JTextField JVeiculoPlaca;
    private javax.swing.JButton SaveButton4;
    private javax.swing.JButton cancelButton4;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
